# Generated by Django 6.1.1 on 2026-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_username",
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Chat_id пользователя телеграм"),
        ),
    ]
