# Generated by Django 6.1.1 on 2026-09-16 05:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="Действие")),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="Место")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="Вознаграждение")),
            ],
            options={
                "verbose_name": "Награда",
                "verbose_name_plural": "Награды",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "duration",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время на выполнение (в секундах)",
                    ),
                ),
                (
                    "execution_time",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Следующее выполнение"),
                ),
                (
                    "period",
                    models.SmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность",
                    ),
                ),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичной привычки")),
                ("is_disabled", models.BooleanField(default=False, verbose_name="Отключена")),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="habits",
                        to="habits.action",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        error_messages={"invalid": "Selected habit is invalid. Please select pleasant habit."},
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связаная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="habits",
                        to="habits.location",
                        verbose_name="Место",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="habits",
                        to="habits.reward",
                        verbose_name="Вознаграждение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_pleasant", True), ("related_habit__isnull", True), ("reward__isnull", True)),
                            models.Q(
                                ("is_pleasant", False), ("related_habit__isnull", False), ("reward__isnull", True)
                            ),
                            models.Q(
                                ("is_pleasant", False), ("related_habit__isnull", True), ("reward__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="pleasant_habit_or_related_habit_or_reward",
                        violation_error_message="Pleasant habit can't have either relate_habit or reward. "
                        "Useful habit can have either related habit or reward",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration__gte", 1), ("duration__lte", 120)),
                        name="duration_range_1_to_120",
                        violation_error_message="Duration cand be more than 120 seconds.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period__gte", 1), ("period__lte", 7)),
                        name="period_range_1_to_7",
                        violation_error_message="Habit should be performed at least once a week.",
                    ),
                ],
            },
        ),
    ]
